version: '3'
services: 
  frontend:
    container_name: frontend
    build: ./frontend
    command: yarn run start
    ports: 
      - 3000:3000

  backend:
    container_name: backend
    build: ./backend
    command: yarn nodemon 
    ports: 
      - 5000:5000
    depends_on:
      - mongo 

  mongo: 
    container_name: mongo 
    image: mongo
    ports:
      - 27017:27017