version: "3"
services:
  backend:
    container_name: backend
    build: .
    command: yarn nodemon
    ports:
      - 5000:5000
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
